export interface CurrencyInfo {
  code: string;
  name: string;
  symbol: string;
}

export const WORLD_CURRENCIES: CurrencyInfo[] = [
  { code: "USD", name: "United States Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
  { code: "CLP", name: "Chilean Peso", symbol: "$" },
  { code: "COP", name: "Colombian Peso", symbol: "$" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "Rs" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع." },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
  { code: "ALL", name: "Albanian Lek", symbol: "L" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏" },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
  { code: "BMD", name: "Bermudian Dollar", symbol: "$" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs." },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu." },
  { code: "BWP", name: "Botswanan Pula", symbol: "P" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡" },
  { code: "CUP", name: "Cuban Peso", symbol: "$MN" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$" },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "£" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾" },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
  { code: "GYD", name: "Guyanaese Dollar", symbol: "G$" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF" },
  { code: "KPW", name: "North Korean Won", symbol: "₩" },
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
  { code: "LAK", name: "Lao Kip", symbol: "₭" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮" },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин." },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "SR" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh.So." },
  { code: "SRD", name: "Surinamese Dollar", symbol: "Sr$" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "SS£" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { code: "SVC", name: "Salvadoran Colón", symbol: "₡" },
  { code: "SYP", name: "Syrian Pound", symbol: "LS" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "E" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "T" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
  { code: "UZS", name: "Uzbekistan Som", symbol: "so'm" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT" },
  { code: "WST", name: "Samoan Tala", symbol: "WS$" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
  { code: "XPF", name: "CFP Franc", symbol: "₣" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "ZWG", name: "Zimbabwean Gold", symbol: "ZiG" },
];

const FALLBACK_RATES: Record<string, number> = {
  USD: 1.0,
  EUR: 0.92,
  GBP: 0.78,
  JPY: 154.5,
  CAD: 1.38,
  AUD: 1.52,
  CHF: 0.88,
  CNY: 7.23,
  INR: 84.4,
  BDT: 119.5,
  SGD: 1.34,
  AED: 3.67,
  SAR: 3.75,
  ZAR: 18.2,
  BRL: 5.75,
  MXN: 20.3,
  EGP: 49.2,
  KRW: 1395.0,
  THB: 34.5,
  IDR: 15800.0,
  MYR: 4.45,
  NZD: 1.68,
  SEK: 10.8,
  NOK: 10.9,
  DKK: 6.87,
  PLN: 4.05,
  TRY: 34.2,
  RUB: 97.5,
  HKD: 7.78,
  TWD: 32.1,
  ARS: 995.0,
  CLP: 970.0,
  COP: 4350.0,
  PEN: 3.77,
  VND: 25400.0,
  PKR: 278.0,
  LKR: 292.0,
  NPR: 134.5,
  NGN: 1680.0,
  KES: 129.0,
  GHS: 16.2,
  MAD: 9.85,
  QAR: 3.64,
  KWD: 0.31,
  OMR: 0.385,
  BHD: 0.376,
  JOD: 0.71,
  ILS: 3.72,
  PHP: 58.6,
  CZK: 23.4,
  HUF: 375.0,
  RON: 4.58,
  BGN: 1.80,
  HRK: 6.93,
  ISK: 137.5,
  AFN: 68.5,
  ALL: 90.2,
  AMD: 387.0,
  ANG: 1.80,
  AOA: 915.0,
  AWG: 1.80,
  AZN: 1.70,
  BAM: 1.80,
  BBD: 2.0,
  BIF: 2890.0,
  BMD: 1.0,
  BND: 1.34,
  BOB: 6.91,
  BSD: 1.0,
  BTN: 84.4,
  BWP: 13.5,
  BYN: 3.27,
  BZD: 2.0,
  CDF: 2850.0,
  CRC: 512.0,
  CUP: 24.0,
  CVE: 101.5,
  DJF: 177.7,
  DOP: 60.1,
  DZD: 133.5,
  ERN: 15.0,
  ETB: 122.0,
  FJD: 2.25,
  FKP: 0.78,
  GEL: 2.73,
  GIP: 0.78,
  GMD: 70.5,
  GNF: 8600.0,
  GTQ: 7.72,
  GYD: 209.0,
  HNL: 25.0,
  HTG: 131.5,
  IQD: 1310.0,
  IRR: 42000.0,
  JMD: 158.0,
  KHR: 4050.0,
  KMF: 452.0,
  KPW: 900.0,
  KYD: 0.83,
  KZT: 495.0,
  LAK: 22000.0,
  LBP: 89500.0,
  LRD: 194.0,
  LSL: 18.2,
  LYD: 4.85,
  MDL: 18.1,
  MGA: 4600.0,
  MKD: 56.6,
  MMK: 2100.0,
  MNT: 3400.0,
  MOP: 8.02,
  MRU: 39.8,
  MUR: 46.5,
  MVR: 15.4,
  MWK: 1730.0,
  MZN: 63.8,
  NAD: 18.2,
  NIO: 36.8,
  PAB: 1.0,
  PGK: 3.95,
  PYG: 7800.0,
  RSD: 108.0,
  RWF: 1370.0,
  SBD: 8.45,
  SCR: 13.8,
  SDG: 600.0,
  SHP: 0.78,
  SLE: 22.5,
  SOS: 570.0,
  SRD: 31.5,
  SSP: 1300.0,
  STN: 22.5,
  SVC: 8.75,
  SYP: 13000.0,
  SZL: 18.2,
  TJS: 10.6,
  TMT: 3.50,
  TND: 3.08,
  TOP: 2.35,
  TTD: 6.78,
  TZS: 2680.0,
  UAH: 41.3,
  UGX: 3670.0,
  UYU: 41.8,
  UZS: 12800.0,
  VUV: 119.0,
  WST: 2.75,
  XAF: 603.5,
  XCD: 2.70,
  XOF: 603.5,
  XPF: 110.0,
  YER: 250.0,
  ZMW: 26.8,
  ZWG: 13.8,
};

export interface ExchangeRateResult {
  base: string;
  rates: Record<string, number>;
  asOf: string;
  isLive: boolean;
}

export async function getLiveExchangeRates(baseCurrency: string = "USD"): Promise<ExchangeRateResult> {
  const base = baseCurrency.toUpperCase();
  try {
    const res = await fetch(`https://open.er-api.com/v6/latest/${base}`, {
      next: { revalidate: 14400 },
    });

    if (res.ok) {
      const data = await res.json();
      if (data && data.rates) {
        return {
          base,
          rates: data.rates,
          asOf: new Date(data.time_last_update_utc || Date.now()).toISOString(),
          isLive: true,
        };
      }
    }
  } catch (error) {
    console.warn("Currency API fetch failed, using fallback currency matrix:", error);
  }

  const baseUsdRate = FALLBACK_RATES[base] || 1.0;
  const rates: Record<string, number> = {};

  for (const [curr, usdRate] of Object.entries(FALLBACK_RATES)) {
    rates[curr] = Math.round((usdRate / baseUsdRate) * 10000) / 10000;
  }

  return {
    base,
    rates,
    asOf: new Date().toISOString(),
    isLive: false,
  };
}

export function convertCurrency(
  amount: number,
  fromCurr: string,
  toCurr: string,
  ratesMatrix: Record<string, number>
): number {
  if (fromCurr === toCurr || !amount) return amount;
  const fromRate = ratesMatrix[fromCurr] || FALLBACK_RATES[fromCurr] || 1.0;
  const toRate = ratesMatrix[toCurr] || FALLBACK_RATES[toCurr] || 1.0;

  const inUsd = amount / fromRate;
  const converted = inUsd * toRate;
  return Math.round(converted * 100) / 100;
}
